#!/bin/bash
clear
source ShellBot.sh
touch lista

[[ ! -e RESET ]] && touch RESET
api_bot=$1
ShellBot.init --token "$api_bot" --monitor --flush
ShellBot.username

# - Funcao menu
menu() {
    local msg
        msg="◇──────────────────◇\n"
        msg+="<b>•🔹• HELLO WELCOME •🔹•</b>\n"
        msg+="◇──────────────────◇\n\n"
        msg+="ssh account R$ 10/Month"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - funcao criar ssh
criarteste() {
    [[ $(grep -wc ${callback_query_from_id} lista) != '0' ]] && {
      ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "YOU HAVE ALREADY CREATED YOUR TEST!"
      return 0
    }
    usuario=$(echo TESTE$(( RANDOM% + 250 )))
    senha=$((RANDOM% + 99999))
    limite='1'
    tempo='1'
    tuserdate=$(date '+%C%y/%m/%d' -d " +1 days")
    useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
    (echo "$senha";echo "$senha") | passwd $usuario > /dev/null 2>&1
    echo "$senha" > /etc/VPSManager/senha/$usuario
    echo "$usuario $limite" >> /root/usuarios.db
    echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/VPSManager/senha/$usuario > /dev/null 2>&1
rm -rf /etc/VPSManager/userteste/$usuario.sh" > /etc/VPSManager/userteste/$usuario.sh
    chmod +x /etc/VPSManager/userteste/$usuario.sh
    at -f /etc/VPSManager/userteste/$usuario.sh now + $tempo hour > /dev/null 2>&1
    echo ${callback_query_from_id} >> lista
    # - ENVIA O SSH
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "✅ <b>successfully created</b> ✅\n\nSERVER: $(cat /etc/IP) \n\nUSER: <code>$usuario</code>\nPASSWORD: <code>$senha</code>\n\n⏳ Expires in: $tempo Hora")" \
    --parse_mode html
    return 0
}

#informacoes usuario
infouser () {
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
	--text "$(echo -e "Nome:  ${message_from_first_name[$(ShellBot.ListUpdates)]}\nUser: @${message_from_username[$(ShellBot.ListUpdates)]:-null}")\nID: ${message_from_id[$(ShellBot.ListUpdates)]} " \
	--parse_mode html
	return 0
}

#informacoes usuario
pix () {
	 ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
	--text "$(echo -e "<b>ssh account R$ 10/Month \n\nCOPY THE RANDOM PIX KEY</b>\n <code>b54bc1c3-c892-4b3a-a7ac-73a46f9eefa3</code>")" \
	--parse_mode html
	return 0
}

unset botao1
botao1=''
ShellBot.InlineKeyboardButton --button 'botao1' --line 1 --text 'CREATE TEST' --callback_data 'gerarssh'
ShellBot.InlineKeyboardButton --button 'botao1' --line 2 --text 'TELEGRAM CONTACT' --callback_data '2' --url 'https://https://t.me/SD_VPS_MANAGER' 
ShellBot.InlineKeyboardButton --button 'botao1' --line 3 --text 'TELEGRAM CONTACT' --callback_data '3' --url 'https://https://t.me/SD_VPS_MANAGER' 
ShellBot.InlineKeyboardButton --button 'botao1' --line 4 --text 'TELEGRAM CONTACT' --callback_data 'pay'
ShellBot.InlineKeyboardButton --button 'botao1' --line 4 --text 'TELEGRAM CONTACT' --callback_data '4' --url 'https://https://t.me/SD_VPS_MANAGER' 
ShellBot.regHandleFunction --function criarteste --callback_data gerarssh
ShellBot.regHandleFunction --function pix --callback_data pay

unset keyboard1
keyboard1="$(ShellBot.InlineKeyboardMarkup -b 'botao1')"
while :; do
   [[ "$(date +%d +5days)" != "$(cat RESET)" ]] && {
   	echo $(date +%d +5days) > RESET
   	echo ' ' > lista
   }
  ShellBot.getUpdates --limit 100 --offset $(ShellBot.OffsetNext) --timeout 30
  for id in $(ShellBot.ListUpdates); do
    (
      ShellBot.watchHandle --callback_data ${callback_query_data[$id]}
      comando=(${message_text[$id]})
      [[ "${comando[0]}" = "/menu"  || "${comando[0]}" = "/start" ]] && menu
      [[ "${comando[0]}" = "/id"  ]] && infouser
    ) &
  done
done
