#!/bin/bash
IP=$(cat /etc/IP)
generate_random_pass() {
    local length=$1
    local chars=({a..z} {A..Z} {0..9} )
    local str=""

    for (( i=0; i<$length; i++)); do
        local rand_idx=$(( RANDOM % ${#chars[@]} ))
        str+=${chars[$rand_idx]}
    done

    echo "$str"
}
check_username() {
    awk -F : ' { print $1 }' /etc/passwd > /tmp/users
    if grep -Fxq "$1" /tmp/users
    then
        tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "User {$1} already exists." ; echo "" ; tput sgr0
        exit 1
    fi
}


tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "Create bulk user" ; tput sgr0
echo ""
echo -ne "\033[1;32mNumber of users\033[1;37m: "; read num
if [[ -z $num ]] || [[ ${a} != ?(+|-)+([0-9]) ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Invalid number of users." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mUsername\033[1;37m: "; read name
if [[ -z $name ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid name." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mStarting number\033[1;37m: "; read startnum
if [[ -z $startnum ]] || [[ ${a} != ?(+|-)+([0-9]) ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Invalid starting number." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mPassword length\033[1;37m: "; read passlength
if [[ -z $passlength ]] || [[ $passlength -lt 4 ]] || [[ ${a} != ?(+|-)+([0-9]) ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Length must be number and >=4" ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mDays\033[1;37m: "; read days
if [[ -z $days ]] || [[ ${a} != ?(+|-)+([0-9]) ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid number of days." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mLimit\033[1;37m: "; read limit
if [[ -z $limit ]] || [[ ${a} != ?(+|-)+([0-9]) ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit.
" ; echo "" ; tput sgr0
	exit 1
fi
echo "Host,Username,Password,Limit,Exp">/tmp/bulkusers
for (( i=$startnum; i<=($startnum+$num); i++ )); do
    username=$name$i
    password=$(generate_random_pass $passlength)
    pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
    useradd -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
    echo "$password" >/etc/VPSManager/senha/$username
    echo "$username $limit $days 0" >>/root/usuarios.db
    echo "$IP,$username,$password,$limit,$days" >>/tmp/bulkusers
done
output="/root/bulkusers-$(date "+%Y-%m-%d-%H-%M-%S")"
column -t -s $',' /tmp/bulkusers > $output






clear
    echo -e "\033[1;32m===================================="
    echo -e "\033[1;32m   🐉ㅤDRAGON VPS MANAGERㅤ🐉  " 
    echo -e "\033[1;32m===================================="
    echo ""
    echo -e "\033[1;37m◈─────⪧ BULK SSH ACCOUNTS ⪦─────◈"
    echo ""
    awk -F' ' '{print "\033[34m "$1"\033[0m\033[32m "$2"\033[0m\033[33m "$3"\033[0m\033[31m "$4"\033[0m\033[36m "$5"\033[0m"}' $output | column -t -s $' '
    echo ""
    echo ""
    echo -e "\033[1;37m◈─────⪧    End of list    ⪦─────◈"
    echo ""
    echo ""
    echo -e "\033[31mUser information saved to\033[0m\033[37m:"
    echo -e "\033[0m\033[32m      "$output"\033[0m"





exit
